[package]
name = "feedrick"
version = "0.1.0"
authors = ["sean billig <sean.billig@gmail.com>"]
edition = "2018"

[dependencies]
buffered_offset_reader = "0.3"
clap = "~2.32.0"
flumedb = { git = "https://github.com/sunrise-choir/flumedb-rs" }
serde_json = "1.0"
termion = "1"
